name: learn-github-actions
on: [push]

jobs:

  use-variables: 
    runs-on: macOS-latest
    name: Checkout and print repo and workflow info
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Use variables to print text about this workflow and repo
        run: |
          echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      - name: Use variables to list files in the repository and print job status
        run: |
          ls ${{ github.workspace }}
          echo "ðŸ This job's status is ${{ job.status }}."
  
  shell-steps:
    runs-on: macOS-latest
    name: Make a temporary object, an artifact
    steps:
      
      - name: shell script
        run: echo Look, it's text!'
          
      - name: Make a temporary object, an artifact
        run: |
          mkdir -p data/artifact
          echo hello > data/world.txt
      
      - name: Upload artifact, to persist for 365 days
        uses: actions/upload-artifact@v2
        with:
          name: hello-world-text-artifact
          path: data/world.txt
          retention-days: 365

      - shell: bash
        run: |
          expr 1 + 2 > output.log
          
      - name: Upload artifact, to persist for 365 days
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log
          retention-days: 365

  R-steps: 
    runs-on: macOS-latest
    name: Make files and store to repo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@master
        
      - name: Run some R code to make a .txt file
        run: |
          mkdir -p data/my_file1.txt
          Rscript -e 'writeLines("text_lines", "my_file2.txt")'
      
      - name: Commit and push artifact and .txt file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add txt file"
          git push 
      
          
